name: xinception
description: xinception 客户端

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_statusbarcolor: ^0.2.3
  crypto: ^3.0.0
  json_annotation: any
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: any
  hive_generator: any
  build_runner: any
  json_serializable: any
flutter:
  uses-material-design: true
  assets:
    - images/bg.svg

